#!/bin/sh
# Splikan - S2S (Student-to-Student) peer tutoring made easy!
# Copyright (C) 2025  Joao Augusto Costa Branco Marado Torres
# <torres.dev@disroot.org>
#
# This file is part of Splikan.
#
# Splikan is free software: you can redistribute it and/or modify it under the
# terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# Splikan is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Splikan.  If not, see <https://www.gnu.org/licenses/>.
if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --type=bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

VERSION_FILE="VERSION"

if [ ! -f "$VERSION_FILE" ]; then
	cat <<\EOF
Error: VERSION file is missing."

Create a file named `VERSION` and write the SemVer complient version of the
project.

The initial version should be `0.1.0`.
EOF
    exit 1
fi

VERSION=$(cat "$VERSION_FILE")

SEMVER_REGEX="^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$"

perl -e "exit ('$VERSION' =~ /$SEMVER_REGEX/ ? 0 : 1)" || {
	cat "Error: Version '$VERSION' is not valid SemVer."
    exit 1
}

deno task version_update


if ! deno task citation_validate; then
  echo "\`CITATION.cff\` has invalid formatting"
  exit 1
fi

if ! deno fmt --unstable-sql --check; then
  echo "Please run \`deno fmt --unstable-sql\`."
  exit 1
fi

if ! deno lint --rules-include=no-console; then
  echo "Please run \`deno lint --rules-include=no-console\`."
  exit 1
fi

test_output=$(deno test 2>&1)
test_exit_code=$?

if echo "$test_output" | grep -q "No test modules found" || [ $test_exit_code -eq 0 ]; then
    :
else
    exit 1
fi

if ! deno task test; then
  echo "Please run \`deno task test\`."
  exit 1
fi

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test "$(git diff-index --cached --name-only --diff-filter=A -z "$against" |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c)" != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached "$against" --
