#!/bin/sh
# Splikan - S2S (Student-to-Student) peer tutoring made easy!
# Copyright (C) 2025  Joao Augusto Costa Branco Marado Torres
# <torres.dev@disroot.org>
#
# This file is part of Splikan.
#
# Splikan is free software: you can redistribute it and/or modify it under the
# terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# Splikan is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Splikan.  If not, see <https://www.gnu.org/licenses/>.

# An example hook script to prepare the commit log message.
# Called by "git commit" with the name of the file that has the
# commit message, followed by the description of the commit
# message's source.  The hook's purpose is to edit the commit
# message file.  If the hook fails with a non-zero status,
# the commit is aborted.
#
# To enable this hook, rename this file to "prepare-commit-msg".

# This hook includes three examples. The first one removes the
# "# Please enter the commit message..." help message.
#
# The second includes the output of "git diff --name-status -r"
# into the message, just before the "git status" output.  It is
# commented because it doesn't cope with --amend or with squashed
# commits.
#
# The third example adds a Signed-off-by line to the message, that can
# still be edited.  This is rarely a good idea.

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

/usr/bin/perl -i.bak -ne 'print unless(m/^. Please enter the commit message/..m/^#$/)' "$COMMIT_MSG_FILE"

# case "$COMMIT_SOURCE,$SHA1" in
#  ,|template,)
#    /usr/bin/perl -i.bak -pe '
#       print "\n" . `git diff --cached --name-status -r`
# 	 if /^#/ && $first++ == 0' "$COMMIT_MSG_FILE" ;;
#  *) ;;
# esac

# SOB=$(git var GIT_COMMITTER_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
# git interpret-trailers --in-place --trailer "$SOB" "$COMMIT_MSG_FILE"
# if test -z "$COMMIT_SOURCE"
# then
#   /usr/bin/perl -i.bak -pe 'print "\n" if !$first_line++' "$COMMIT_MSG_FILE"
# fi

TYPES=$(cat <<'EOF'
# Types can be:
# * build
# * chore
# * ci
# * docs
# * feat
# * fix
# * perf
# * refactor
# * revert
# * style
# * test
EOF
)

if test -z "$COMMIT_SOURCE"
then
    temp_file0=$(mktemp)
    temp_file1=$(mktemp)

    printf "%s\n$TYPES\n\n%s\n\n%s\n" "<type>[optional scope]: <description>" \
        "[optional body]" \
        "[optional footer(s)]" > "$temp_file0"

    cat "$temp_file0" "$1" > "$temp_file1" && mv "$temp_file1" "$1"
fi
